Repository cds-snc/covid-alert-portal, pull requests merged in 2021-07, with the labels that each got.

#676 Fix/required field error change
  locale/fr/LC_MESSAGES/django.mo
  locale/fr/LC_MESSAGES/django.po
  portal/forms.py
  register/tests.py
Labels: needs dev review

#678 Changing the Send alert button to green instead of yellow
  outbreaks/templates/confirm.html
Labels: needs dev review

#684 fix: remove QR code DNS health check
  config/terraform/aws/route53.tf
Labels: bug

#679 Fix/back link fix
  locale/fr/LC_MESSAGES/django.mo
  locale/fr/LC_MESSAGES/django.po
  outbreaks/templates/history.html
Labels: needs dev review

#680 Adding missing "Step 3 of 3" to the Send Alerts page
  locale/fr/LC_MESSAGES/django.mo
  locale/fr/LC_MESSAGES/django.po
  outbreaks/templates/confirm.html
Labels: needs dev review

#674 new fields and support for venue type in survey
  locale/fr/LC_MESSAGES/django.po
  register/admin.py
  register/migrations/0007_survey_query_params.py
  register/models.py
Labels: needs dev review

#685 Fix/send alert menu fix
  portal/templates/includes/nav_main.html
Labels: needs dev review

#690 feat: enable AWS Shield for QR code
  .github/workflows/terraform.yml
  config/terraform/aws/shield.tf
Labels: enhancement

#697 Fix send alerts content as per issue #694
  about/templates/about/6_sending_qr_alerts.html
  locale/fr/LC_MESSAGES/django.mo
  locale/fr/LC_MESSAGES/django.po
Labels: needs dev review

#677 Date & time selection bug fixes, future date and time range limit on alerting
  locale/fr/LC_MESSAGES/django.po
  outbreaks/forms.py
  outbreaks/tests.py
  profiles/static/js/script.js
Labels: needs dev review

#699 Fixing french apostrophes
  locale/fr/LC_MESSAGES/django.mo
  locale/fr/LC_MESSAGES/django.po
Labels: needs dev review
