Repository cds-snc/covid-alert-portal, pull requests merged in 2021-06, with the labels that each got.

#568 More content updates
  locale/fr/LC_MESSAGES/django.mo
  locale/fr/LC_MESSAGES/django.po
  register/forms.py
  register/templates/register/help_page.html
  register/templates/register/location_name.html
  register/templates/register/location_unavailable.html
  register/templates/register/registrant_email_submitted.html
  register/templates/register/start.html
Labels: needs dev review

#551 Split notify service between portal and qrcode/register apps
  .github/workflows/terraform.yml
  config/terraform/aws/bootstrap/provider.tf
  config/terraform/aws/bootstrap/versions.tf
  config/terraform/aws/cloudwatch_qrcode.tf
  config/terraform/aws/ecr.tf
  config/terraform/aws/ecs.tf
  config/terraform/aws/iam.tf
  config/terraform/aws/lb_portal.tf
  config/terraform/aws/lb_qrcode.tf
  config/terraform/aws/modules/codedeploy/variables.tf
  config/terraform/aws/s3.tf
  config/terraform/aws/secrets.tf
  config/terraform/aws/task-definitions/covid-portal.json
  config/terraform/aws/variables.tf
  portal/settings.py
Labels: needs dev review

#570 Fix/back button and explicit breadcrumb type links
  outbreaks/templates/confirm.html
  outbreaks/templates/datetime.html
  outbreaks/templates/details.html
  outbreaks/templates/profile.html
  outbreaks/templates/severity.html
  outbreaks/tests.py
  outbreaks/urls.py
  outbreaks/views.py
  profiles/static/js/script.js
Labels: needs dev review

#578 Update tipsheet/instructions with latest
  register/templates/register/posters/instructions-en.pdf
  register/templates/register/posters/instructions-fr.pdf
Labels: needs dev review

#574 Portal nav post login
  announcements/tests.py
  contact/templates/contact/success.html
  covid_key/forms.py
  covid_key/templates/covid_key/generate_key.html
  covid_key/templates/covid_key/key.html
  covid_key/templates/covid_key/landing.html
  covid_key/templates/covid_key/otk_start.html
  covid_key/tests.py
  covid_key/urls.py
  covid_key/views.py
  locale/fr/LC_MESSAGES/django.po
  portal/templates/403.html
  portal/templates/404.html
  portal/templates/includes/footer.html
  portal/templates/includes/nav_main.html
  profiles/static/scss/pages/_covidkey-start.scss
  profiles/static/scss/styles.scss
  profiles/tests.py
Labels: needs dev review

#577 Fix/details severity desc
  locale/fr/LC_MESSAGES/django.po
  outbreaks/forms.py
  outbreaks/models.py
  register/templates/register/privacy.html
  register/templates/register/terms.html
Labels: needs dev review

#622 feat: pin local Terraform version with asdf
  .gitignore
  config/terraform/aws/.tool-versions
Labels: enhancement

#626 fix: ECS service autoscaling targets and policies
  config/terraform/aws/ecs.tf
Labels: bug

#628 feat: add FARGATE capacity provider to ECS cluster
  config/infrastructure/aws/appspec-template.json
  config/terraform/aws/ecs.tf
Labels: bug

#642 updated outbreaks wizard content and selection process
  locale/fr/LC_MESSAGES/django.po
  outbreaks/templates/datetime.html
  outbreaks/views.py
Labels: needs dev review

#647 feat: lower ECS CPU/memory autoscale thresholds
  config/terraform/aws/variables.tf
Labels: enhancement

#644 Reordering QR code and instructions in poster
  register/utils.py
Labels: needs dev review

#624 Accessibility fixes for mobile search , date form and details of exposure
  outbreaks/templates/datetime.html
  outbreaks/templates/details.html
  outbreaks/templates/history.html
  outbreaks/templates/search.html
  profiles/static/scss/components/forms/_form.scss
  profiles/static/scss/pages/_outbreaks-datetime.scss
  profiles/static/scss/pages/_outbreaks-search.scss
Labels: needs dev review

#640 Fix/french abbrev fix
  profiles/static/js/datepicker.js
Labels: needs dev review

#650 add location to ensure join on query when sorting by date
  outbreaks/views.py
Labels: needs dev review

#654 Enhance survey filters in Django admin
  locale/fr/LC_MESSAGES/django.po
  register/admin.py
  register/models.py
Labels: needs dev review
