Repository cds-snc/covid-alert-portal, pull requests merged in 2021-04, with the labels that each got.

#458 Send Email Again button
  locale/fr/LC_MESSAGES/django.mo
  locale/fr/LC_MESSAGES/django.po
  register/templates/register/registrant_email_submitted.html
  register/views.py
Labels: ready for dev review

#457 Implement Sending Support Tickets to ISED
  locale/fr/LC_MESSAGES/django.mo
  locale/fr/LC_MESSAGES/django.po
  portal/.env.example
  portal/settings.py
  register/forms.py
  register/templates/register/contact_us.html
  register/views.py
Labels: dev review

#462 Remove Registrant Name step
  locale/fr/LC_MESSAGES/django.mo
  locale/fr/LC_MESSAGES/django.po
  register/admin.py
  register/forms.py
  register/migrations/0002_remove_registrant_name.py
  register/models.py
  register/templates/register/location_address.html
  register/templates/register/registrant_name.html
  register/templates/register/summary.html
  register/tests.py
  register/urls.py
  register/views.py
Labels: dev review

#463 Change the flow/step order and add step counter
  locale/fr/LC_MESSAGES/django.mo
  locale/fr/LC_MESSAGES/django.po
  register/templates/register/confirmation.html
  register/templates/register/location_address.html
  register/templates/register/location_category.html
  register/templates/register/location_contact.html
  register/templates/register/location_name.html
  register/templates/register/summary.html
  register/urls.py
  register/views.py
Labels: dev review

#464 Update the canada post trial api key
  register/static/register/js/address-autocomplete.js
Labels: dev review

#465 Updated Summary Screen
  locale/fr/LC_MESSAGES/django.mo
  locale/fr/LC_MESSAGES/django.po
  profiles/static/scss/components/_tag.scss
  register/templates/register/summary.html
Labels: needs dev review

#466 Update package dependencies
  Pipfile.lock
Labels: needs dev review

#453 Huge content changes
  CHANGELOG.md
  about/templates/about/2_create_account.html
  about/templates/about/4_give_a_key.html
  about/templates/about/5_help_patient_enter_key.html
  about/templates/about/6_admin_accounts.html
  about/templates/includes/_nav_about.html
  about/tests.py
  backup_codes/signals.py
  backup_codes/templates/backup_codes/admin_backup_codes_list.html
  backup_codes/templates/backup_codes/backup_codes_help.html
  backup_codes/templates/backup_codes/backup_codes_list.html
  backup_codes/templates/backup_codes/signup_backup_codes_list.html
  backup_codes/tests.py
  contact/forms.py
  locale/fr/LC_MESSAGES/django.mo
  locale/fr/LC_MESSAGES/django.po
  portal/templates/registration/login.html
  profiles/forms.py
  profiles/migrations/0009_add_more_provinces.py
  profiles/migrations/0016_update_description_name_phone_number.py
  profiles/migrations/0017_update_description_phone_number.py
  profiles/models.py
  profiles/templates/invitations/templates/invite_expired.html
  profiles/templates/otp/email/token.html
  profiles/templates/profiles/2fa-resend.html
  profiles/templates/profiles/2fa.html
  profiles/templates/profiles/edit.html
  profiles/templates/profiles/healthcareuser_detail.html
  profiles/templates/profiles/terms.html
  profiles/tests.py
  profiles/views.py
Labels: needs content review, needs dev review

#467 Add relationship between location and registrant
  register/migrations/0003_location_registrant.py
  register/models.py
  register/views.py
Labels: needs dev review

#470 Exclude Registrant from Location search/match
  register/views.py
Labels: needs dev review

#471 Update translations, remove obsolete, small fix
  locale/fr/LC_MESSAGES/django.mo
  locale/fr/LC_MESSAGES/django.po
  register/templates/register/registrant_email_submitted.html
Labels: needs dev review

#472 Feature/confirmation page adjustments
  locale/fr/LC_MESSAGES/django.po
  register/static/register/img/PDF_icon_black.svg
  register/static/register/img/PDF_icon_white.svg
  register/static/register/img/hand_reminder.svg
  register/static/register/scss/_custom.scss
  register/templates/register/confirmation.html
Labels: needs dev review

#473 added new radio button
  locale/fr/LC_MESSAGES/django.po
  register/forms.py
  register/static/register/scss/_custom.scss
  register/templates/register/location_category.html
Labels: needs dev review

#468 Extension number
  locale/fr/LC_MESSAGES/django.po
  register/forms.py
  register/migrations/0004_location_contact_phone_ext.py
  register/models.py
  register/static/register/js/phone-extension.js
  register/static/register/scss/_custom.scss
  register/static/register/scss/_qr-support-page.scss
  register/templates/register/includes/phone_extension.html
  register/templates/register/location_contact.html
  register/templates/register/summary.html
  register/views.py
  register/widgets.py
Labels: needs dev review

#475 Update poster svg templates with latest design
  register/templates/register/confirmation.html
  register/templates/register/posters/en.svg
  register/templates/register/posters/fr.svg
  register/utils.py
Labels: needs dev review

#476 fix sass syntax error
  register/static/register/scss/_custom.scss
Labels: needs dev review

#469 Add a generated migration
  profiles/migrations/0022_alter_healthcareuser_phone_number.py
Labels: needs dev review

#480 Add step to verify sass files can compile
  .github/workflows/main.yml
Labels: needs dev review

#479 Fix image alignment issue on confirmation
  register/static/register/scss/_custom.scss
Labels: needs dev review

#478 Bugfix/confirmation page redirect
  register/tests.py
  register/views.py
Labels: needs dev review

#487 Address Autocomplete support for Internet Explorer 11
  register/static/register/js/address-autocomplete.js
Labels: needs dev review

#485 Update Start page content
  locale/fr/LC_MESSAGES/django.mo
  locale/fr/LC_MESSAGES/django.po
  register/templates/register/start.html
Labels: needs dev review

#488 Add location address to poster email subject
  register/views.py
Labels: needs dev review

#483 Refactor - Create base form template for more re-usability
  portal/templates/includes/cds_form.html
  register/templates/register/includes/contact_form.html
  register/templates/register/location_contact.html
Labels: needs dev review

#486 Improve interaction design of Date and time selection
  locale/fr/LC_MESSAGES/django.po
  outbreaks/forms.py
  outbreaks/templates/confirm.html
  outbreaks/templates/confirmed.html
  outbreaks/templates/datetime.html
  outbreaks/templatetags/fieldset_date.py
  outbreaks/templatetags/form_date.py
  outbreaks/tests.py
  outbreaks/urls.py
  outbreaks/views.py
  portal/settings.py
  profiles/static/img/access_time_24px.svg
  profiles/static/img/calendar_today_24px.svg
  profiles/static/js/datepicker.js
  profiles/static/js/script.js
  profiles/static/scss/_variables.scss
  profiles/static/scss/components/_messages.scss
  profiles/static/scss/components/forms/_error.scss
  profiles/static/scss/components/forms/_input.scss
  profiles/static/scss/pages/_outbreaks-datetime.scss
  profiles/static/scss/styles.scss
Labels: needs translation

#496 Display the French download link first when in the French interface
  locale/fr/LC_MESSAGES/django.mo
  register/static/register/scss/_custom.scss
  register/templates/register/confirmation.html
Labels: needs dev review

#497 Add data length validation to text inputs
  register/forms.py
Labels: needs dev review

#502 updated css for targetted year input resize
  profiles/static/scss/components/forms/_form.scss
Labels: needs dev review

#506 Display date and time of password changed
  profiles/views.py
Labels: needs dev review

#493 new page created and help page updated with new content
  locale/fr/LC_MESSAGES/django.po
  profiles/static/scss/components/_messages.scss
  register/static/register/img/lightbulb_24px.svg
  register/static/register/scss/_custom.scss
  register/templates/register/confirmation.html
  register/templates/register/help_page.html
  register/templates/register/how_display_poster.html
  register/templates/register/includes/footer.html
  register/templates/register/qr_support_page.html
  register/templates/register/start.html
  register/urls.py
  register/views.py
Labels: needs dev review

#500 Expand searchable params on Location search
  .github/workflows/coverage.yml
  .github/workflows/main.yml
  outbreaks/views.py
Labels: needs dev review
